title: Portfolio
email: bethmitchell24@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Elizabeth Mitchell's Portfolio site
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://eam5.github.io/portfolio" # the base hostname & protocol for your site, e.g. http://example.com
github_username: eam5

# Build settings
#theme: minima

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

sass:
  sass_dir: _sass

#Build Settings
markdown: kramdown